services:
  container1:
    image: filter_and_verify:container1
    container_name: container1
    volumes: 
      - .:/data_volume
    ports:
      - 6000:6000
    depends_on:
      - container2
    networks:
      - default

  container2:
    image: core_logic:container2
    container_name: container2
    ports:
      - 7000:7000
    networks:
      - default
    volumes: 
      - .:/data_volume

networks:
  default:
    driver: bridge